module.exports = {
  INTERNAL_SERVER_ERROR: "Internal Server Error",
  MISSING_REQUIRED_FIELDS: "Missing Required Fields",
  ERROR_CREATING_CLASSES_STUDENT_TABLE: "Error Creating Student Class Table",
  ERROR_CREATING_FEES_STUDENT_TABLE: "Error Creating Student Fee Table",
  ERROR_CREATING_STUDENT_TABLE: "Error Creating Student Table",
  ERROR_INSERTING_STUDENT: "Error Inserting Student",
  ERROR_FETCHING_STUDENTS: "Error Fetching Students",
  ERROR_DELETING_STUDENT: "Error Deleting Student",
  ERROR_UPDATING_STUDENT: "Error Updating Student",
  ERROR_FETCHING_STUDENT: "Error Fetching Student",
  REG_NO_REQUIRED: "Reg No Required",
  STUDENT_NAME_REQUIRED: "Student Name Required",
  CLASS_ID_REQUIRED: "Class ID Required",
  CLASS_NOT_FOUND: "Class Not Found",
  ID_REQUIRED: "ID Required",
  STUDENT_NOT_FOUND: "Student Not Found",
  ERROR_CREATING_STUDENT_CLASS_TABLE: "Error creating student class table",
  ERROR_INSERTING_STUDENT_CLASS: "Error inserting student class",
  ERROR_FETCHING_STUDENT_CLASSES: "Error fetching student classes",
  STUDENT_CLASS_NOT_FOUND: "Student class not found",
  ERROR_FETCHING_STUDENT_CLASS: "Error fetching student class",
  ERROR_UPDATING_STUDENT_CLASS: "Error updating student class",
  ERROR_DELETING_STUDENT_CLASS: "Error deleting student class",
  CLASS_NAME_REQUIRED: "Class name is required",
};
